// Assembly PaintDotNet, Version 4.13.6191.1824

[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyProduct("paint.net")]
[assembly: System.Reflection.AssemblyDescription("Image and photo editing software.")]
[assembly: System.Reflection.AssemblyCompany("dotPDN LLC")]
[assembly: System.Reflection.AssemblyTrademark("paint.net is a registered trademark of dotPDN LLC")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2016 dotPDN LLC, Rick Brewster, and past contributors. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Final")]
[assembly: System.Reflection.AssemblyTitle("paint.net")]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Base", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Core", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Data", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Effects", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Framework", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.Resources", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("PaintDotNet.SystemLayer", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("System.Core", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("System.Drawing", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("System.Windows.Forms", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("WindowsBase", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SetupFrontEnd")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("PdnBench")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("PdnTest")]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.6", FrameworkDisplayName=".NET Framework 4.6")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

